"""empty message

Revision ID: 4e7acdbcaee9
Revises: 3c635b58fec7
Create Date: 2023-07-10 00:21:28.632160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7acdbcaee9'
down_revision = '3c635b58fec7'
branch_labels = None
depends_on = None


def upgrade():
    # ...
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('text',
                              existing_type=sa.VARCHAR(length=500),
                              type_=sa.String(length=255),
                              existing_nullable=False)
        batch_op.alter_column('image',
                              existing_type=sa.VARCHAR(length=100),
                              type_=sa.String(length=255),
                              existing_nullable=True)

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('number_of_questions', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('time', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=6), nullable=False, server_default=''))
    
    # ...



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('difficulty')
        batch_op.drop_column('time')
        batch_op.drop_column('number_of_questions')
        batch_op.drop_column('topic')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    op.create_table('option',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=500), nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=True),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
